services:
  pgdatabase:
    image: postgres:18
    environment:
      - TZ=Asia/Jerusalem
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "budget_postgres_data:/var/lib/postgresql"
    restart: unless-stopped
    
  budget_bot:
    image: ghcr.io/shdrn2402/my_family_budget/budget_bot:latest
    build: .
    environment:
      - TZ=Asia/Jerusalem
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ALLOWED_USER_IDS=${ALLOWED_USER_IDS}
      - DB_HOST=pgdatabase
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - "telegram_data:/logs"
      - "./backups:/app/backups:rw"
    depends_on:
      - pgdatabase
    restart: unless-stopped

volumes:
  budget_postgres_data:
  telegram_data: