services:
  pgdatabase:
    image: postgres:18
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - "budget_postgres_data:/var/lib/postgresql"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:9.16
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    depends_on:
      - pgdatabase
    restart: unless-stopped

  budget_bot:
    image: ghcr.io/shdrn2402/my_family_budget/budget_bot:latest
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ALLOWED_USER_IDS=${ALLOWED_USER_IDS}
      - DB_HOST=pgdatabase
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - "telegram_data:/logs"
      - "./backups:/app/backups:rw"
    depends_on:
      - pgdatabase
    restart: unless-stopped

  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "caddy_data:/data"
      - "caddy_config:/config"
    depends_on:
      - pgadmin


volumes:
  budget_postgres_data:
  pgadmin_data:
  telegram_data:
  caddy_data:
  caddy_config: